---
title: "Social and economic networks"
subtitle: "Handout Exam Part 2"
author: "Juan José Martín y Christian Strasser"
output:
  html_document:
    number_sections: false
    highlight: tango
    toc: yes
    df_print: paged
editor_options: 
  chunk_output_type: console
---



<style type="text/css">

  body {
    background-color: #f6f7fd; 
  }
  
  a:link {
    color: #0174DF;
  }
  
  code.r {
    font-size: 14px;
  } 
  
  div pre {
    background-color:#E0ECF8;
  }
  pre {
    font-size: 14px 
  }
 
  p {
    text-align: justify;
  }
 
    
  h1, h2, h3, h4, h5, h6 {
    color: #737aaa;
  }

  th {  
    background-color:#737aaa;
    color: #FAFAFA;
    padding:5px;
  }
  
  td {
    font-size: 11.5pt;
  } 
  
  tr:nth-child(even){
    background: white;
  }
  
  tr:nth-child(odd){ 
    background-color: #EFF8FB;
  }
</style>

***  


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=8, fig.align="center", echo=TRUE, warning=FALSE, message=FALSE)
library(centiserve)
library(igraph)
```
**1)** In a single sentence, what is the main question addressed in this paper? Why do the authors consider this question relevant and worth answering? After reading the paper, do you consider their answer relevant? Why?

Propone un coeficiente de clustering generalizado y triángulos generalizados con la interpretación relativa.

La principal cuestión que realiza el autor de este papel es saber si existe 'triángulos indirectos' en estructuras de redes sociales. El autor le da importancia a esta cuestion, para ilustrar que puede ser necesario una nueva manera de ver todos los aspectos de estos tipos de redes.

**2)** How does this paper relate to previous work about the question addressed in it?


**3)** What are the main definitions in this paper?

Una nueva definición de coeficiente de clustering. Esta medida es capaz de dar pistas útiles sobre la estructura de la comunidad de la red, cuando los pesos juegan un papel relevante en la inducción de enlaces perdidos entre el nodo.

La predicción de enlaces, que intenta estimar la probabilidad de la existencia de un enlace entre dos vértices basado en enlaces observados y los atributos de los nodos.

**4)** On your behalf, what are the strongest contribution and the greatest drawback of this paper (if any)?


**5)** Do you consider the numerical experiments provided in Section 5 suitable? (I’m not referring to the networks analyzed, but to the computations performed on them.) What conclusions do you extract from these experiments? Do they agree with the authors’ conclusions? What other experiments (on the same networks) would you perform?


**6)** In their experiments, the authors mostly consider cases when $\alpha = 0$ or $\beta = 0$. How would you choose $\alpha$ and $\beta$ so that only really meaningful pseudo-triangles were considered?


**7)** The authors define their generalized clustering coefficient only for undirected networks. How would you generalize it in a sound way to directed networks? Provide a definition that makes sense on some class of weighted directed networks of your choice with some specific meaning of its links (for instance,
non-symmetric friendship networks, trade networks, citation networks with weights the number of times an author has cited another author, . . . )


**8)** At the end of the day, the final value of the generalized clustering coefficient does not depend on the specific weights of the edges in the triangles and “generalized triangles”: each such a triangle only counts 0 or 1 in the definition. Can you think of some sound way to use the weights to “weight” the triangles
and “generalized triangles” in the definition? How could your definition change the experimental results explained in the paper?


**9)** How is the generalized clustering coefficient related to the Strong Triadic Closure Property? Can you find a way to test whether a network satisfies the STCP using this coefficient (together with other indices, of course)?


Now, some technical questions:

**10)** In page 4 the authors say “Our generalized clustering coefficient has a further very relevant property: it assumes unitary value in several situations and not only when the graph is a clique.” Is it true that if an unweighted graph has clustering coefficient 1, then it is a clique? And if we assume moreover that the
graph is connected? Justify your answer.


**11)** In equation (3), page 7, the authors recall Barrat et al’s clustering coefficient for weighted networks. I also introduced this index in my lectures, but equation (3) and my definition do not define the same number. What is the difference? Which one corresponds to Barrat et al’s original definition? How did you check it? If the correct version is the one given in this paper, I probably had a good reason to change it. What was this reason? And, if the correct version is the one I gave in the lectures, did the authors of this paper have a good reason to change it (for instance, to compare it with their proposed coefficient)?


**12)** In equations (4)–(5), page 8, the authors recall Zhang—Horvath’s weighted clustering coefficient for gene co-expression networks. Does it fit with the general philosophy of Kalma–Highman’s indices or Opshal–Panzarasa’s indices as explained in my lectures?


**13)** (Extra bonus) The authors mention that they used R to implement their coefficient and perform their experiments, but they do not provide their implementation. Implement in R their generalized clustering coefficient as well as your proposals in points (7) and (8), and repeat their experiments with your functions, or perform new experiments (for instance, using other networks, using your bounds in point (6), checking point (9), . . . ).

